### ISSUE TITLE
Unable to send chat from the TT+ tray icon 0.2.16

### ISSUE THREAD

**Issue by Kasai** [Frick/ttplus#35]
I can see incoming chat messages from turntable.fm show up in the blue TT+ tray icon 'Chat' tab, but when I type a message to submit to chat it never shows up.  I have asked about 5 other people and none of them were able to write to chat from the blue TT+ tray icon 'Chat' tab.

Ok so I noticed that if I go to the 'Chat' tab, enter a message in the field and hit ENTER the whole window will flash and I can see it say "Turntable.fm room not found" then I see the normal TT+ window again but my message is gone and it has not show up in chat.  

I have attached three images.  One is with the message in the field before I hit ENTER "WindowFlash_1of3.jpg", the screen flash after I hit ENTER "WindowFlash_2of3.jpg", and the screen after that "WindowFlash_3of3.jpg".

The images are in order top to bottom 1,2,3 in this Imgur album.
http://imgur.com/a/Z4ekt

**Comment by Frick** [comment]
Very stupid issue, but finally fixed.  Not sure what changed (likely due to Chrome 21), but it just required a change from listening for a 'keyup' event to listening for a 'keydown' event.  This is fixed in version 0.2.18 available in the Chrome Web Store: https://chrome.google.com/webstore/detail/icgjnmfceciegoonlpegpcaaeggghemc
